### ISSUE TITLE
Circuit Diagram

### ISSUE THREAD

**Issue by rellis-erigon** [3ative/ultimate-fan-project-V3#1]
Is it possible to get a schematic for the design you have used :-) Love the work you have done :-)

**Comment by Desef** [comment]
This looks like a nice project. Please provide the schematic diagram for the project

**Comment by cocolino83** [comment]
I agree ... ✌️😉 a circuit diagram would be great 👍🤩

**Comment by 3ative** [comment]
Soz for the delay guys.
A schematic has been added

**Comment by Desef** [comment]
Nice, clean circuit. Thanks for the (quick? 😁) feedback.

I would have been a bit daring and use the available GPIO pins on that Sonoff, instead of using a port extender. A thin soldering iron point and a magnifying glass makes it possible to tap off of the pads directly.

**Comment by 3ative** [comment]
No worries, happy to share.

Yeah, I have managed to solder directly to the ESP pins before - However, I needed something that 'anyone' could follow without GOD-LIKE soldering skills. LOL
