### ISSUE TITLE
Not so much an issue, but help needed

### ISSUE THREAD

**Issue by jkelly73** [3ative/ultimate-fan-project-V3#2]
Hi and apologies in advance if this is posted in the wrong place...

I have a 3 speed fan controller ([Deta 6914HA](https://www.esphome-devices.com/devices/Deta-Grid-Connect-Smart-Fan-Speed-Controller-with-Touch-Light-Switch)) that has a different button arrangement to your system, essentially a fan ON/OFF and one more button with 3 positions to select speeds 1,2, & 3.

I have had this working very reliably using [code](https://www.esphome-devices.com/devices/Deta-Grid-Connect-Smart-Fan-Speed-Controller-with-Touch-Light-Switch) I came accros on the esphome website and percentages for low, medium & high speeds (before the recent HA core update) but am unable to convert my current esphome to use speeds 1,2 & 3 for the new HA update - I think the current code still uses percentages but represents them as speeds 1,2, & 3.

Ive come accross your code and the additional functionality in your button card via HACS and would like to use this going forward for all my fans but try as I may I dont yet have the knowledge to amend your code to accomodate the Deta 6914HA button arrangements.

Could you provide any assistance please?

Thanks
Jon

**Comment by 3ative** [comment]
Sorry fella/Mam, 
I don't have that controller or have seen one, I made my own from scratch.

If a Core update has stopped yours working, maybe contact the people that changed that code. Also, check out the 'Breaking Changes' for the update to see what changed - That may give you an idea how to fix it. 

Good Luck.
